#!/bin/bash

# The purpose of this script is to accommodate the fact that OBS repo service
# currently does not support multiple/recursive %include directives. We also
# need to keep the nice flow of the "%" sections in .spec


# If output file name is not passed via cmdline, pick the first found candidate
# (safe for all cases except those with multiple device variant .spec files)
FILES=(*.spec*)
SPEC=${1:-${FILES[0]}}
SPEC=${SPEC%.tmpl}

# Order is (will be?) important.
# A package should be created for each of these paths
# Then files which have been mentioned are skipped in future packages
# This needs a %files list generation step
# Only worthwhile if we need to optimise multiple packages
# Do a manual one for prebuilts/ ?

PATHS=""
while read -r path || [[ -n "$path" ]]; do
    echo "Text read from file: $path"
    PATHS="${PATHS} $path"
done < <(cat additional-source.paths dhs/source.paths 2>/dev/null)

# Trim the last space
PATHS=${PATHS% }

REQLIST=""
for path in $PATHS; do
    REQLIST="${REQLIST} %{dhs_feature}-${path//\//-},"
done
# Trim the last ,
REQLIST=${REQLIST%,}

cat <<EOF > package-section
%package dhs-full
Provides: %{dhs_feature}-full
%if %{dhs_legacy}
Provides: droid-bin-src-full
%endif
Group:  System
AutoReqProv: no
Requires(post): /bin/sh
Requires: %{dhs_feature}-dhs-rootdir $REQLIST
Summary: Syspart source for all the src trees to be used for droid-side code building
%description dhs-full
This is the full src tree for the %{dhs_name} manifest.
It is only meant for use in the OBS.

%package dhs-utils
Provides: %{dhs_feature}-dhs-utils
Group:  System
AutoReqProv: no
Requires(post): /bin/sh
Summary: Utilities for droid-side code building for %{device}%{?device_variant}
%description dhs-utils
Summary: Utilities for using the syspart source for droid-side code building.
This package is hardcoded for %{device}%{?device_variant}
It is only meant for use in the OBS.

%package dhs-makefile
Provides: %{dhs_feature}-dhs-makefile
Group:  System
AutoReqProv: no
Requires(post): /bin/sh
Summary: Top level makefile to be used for droid-side code building
%description dhs-makefile
Top level makefile to be used for droid-side code building
It is only meant for use in the OBS.

%package dhs-rootdir
Provides: %{dhs_feature}-dhs-rootdir
Group:  System
AutoReqProv: no
Requires: %{dhs_feature}-dhs-utils %{dhs_feature}-dhs-makefile
Requires(post): /bin/sh
Summary: Top level source files for the device src tree to be used for droid-side code building
%description dhs-rootdir
This is the src tree for the files in the root directory from the %device manifest.
It is only meant for use in the OBS.

EOF


cat <<EOF >files-section
%files dhs-full
# Deliberately empty

%files dhs-utils
%defattr(755,root,root,-)
/usr/bin/droid-make

%post dhs-makefile
# The abuild user is not setup at post time so we use the numeric id
chown 399:399 /home/abuild/src
chown 399:399 /home/abuild/src/droid
chown 399:399 /home/abuild/src/droid/Makefile

%files dhs-makefile
%defattr(-,root,root,-)
/home/abuild/src/droid/Makefile

%post dhs-rootdir
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/

%files dhs-rootdir -f tmp/rootdir.files
%defattr(-,root,root,-)

EOF

for path in $PATHS
do
    pkg=${path//\//-}

    cat <<EOF >> package-section
%package $pkg
Provides: %{dhs_feature}-$pkg
Group:  System
AutoReqProv: no
Requires: %{dhs_feature}-dhs-utils %{dhs_feature}-dhs-makefile
Requires(post): /bin/sh
Summary: Source for the $pkg src tree to be used for droid-side code building
%description $pkg
This is the src tree for the $pkg subdirectory from the %{device} manifest.
It is only meant for use in the OBS.

EOF

cat <<EOF >>files-section
%post $pkg
# The abuild user is not setup at post time so we use the numeric id
chown -R 399:399 /home/abuild/src/droid/$path
%files $pkg
%defattr(-,root,root,-)
/home/abuild/src/droid/$path

EOF

done

# define dhs_trees for use in the .inc processing
echo %define dhs_trees $PATHS > define-trees

cat <<EOF > $SPEC
# This file is autogenerated by running
#  $0 $*
# Please edit $SPEC.tmpl and re-run that command to modify

EOF

# Do an 'include' of packages/files section

cat $SPEC.tmpl >> $SPEC
perl -i -ne 'BEGIN { sub pinc {if (/^%include\s+([\w-.\/]+)$/) { print "# repo service performed : %%include $1\n"; local (*I); open I,"<$1" or print "# Couldnt open $1\n"; while (<I>) { pinc(); }; } else { print $_; }}} pinc;' $SPEC

rm package-section files-section define-trees
